=== learn-medi-ch/medi-course-management/app/schema/medi-course-management-frontend-config-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://flux-eco.fluxlabs.ch/schemas/medi-course-management-frontend-config-schema.json",
  "title": "FluxEcoLearnplacesFrontendConfigSchema",
  "allOf": [
    {
      "$ref": "../../../flux-eco/schemas/flux-eco-app-config-schema.json"
    }
  ],
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "const": "medi-course-management-frontend"
    },
    "inboundsConfig": {
      "httpBindingConfig": {
        "$ref": "../../../flux-eco/schemas/binding-schemas/http-schemas/flux-eco-http-binding-config-schema.json"
      }
    },
    "apiConfig": {
      "$ref": "medi-course-management-frontend-api-config-schema.json"
    },
    "outboundsConfigs": {
      "type": "object",
      "properties": {
        "proxyRequestHandler": {
          "$ref": "../../../flux-eco-http-proxy-request/app/schema/flux-eco-http-proxy-request-config-schema.json"
        }
      },
      "required": [
        "proxyRequestHandler"
      ]
    }
  }
}

=== learn-medi-ch/medi-course-management/app/config/config.json
{
  "$schema": "../schema/medi-course-management-frontend-config-schema.json",
  "name": "medi-course-management-frontend",
  "inboundsConfig": {
    "httpBindingConfig": {
      "server": {
        "host": "${SERVER_HOST}",
        "port": "${SERVER_PORT}"
      },
      "staticFilesPath": "/public",
      "policies": null,
      "routes": {
        "static": {
          "/index.html": {
            "contentType": "text/html"
          },
          "/main.mjs": {
            "contentType": "application/javascript"
          },
          "/**/*.mjs": {
            "contentType": "application/javascript"
          },
          "/**/*.ttf": {
            "contentType": "application/font-ttf"
          },
          "/**/*.wof": {
            "contentType": "application/font-woff"
          }
        },
        "api": {
          "/api/{pageName}/readPageStructure": {
            "contentType": "application/json",
            "parameterNames": ["pageName"],
            "actionName": "readPageStructure",
            "actionType": "requestHandler"
          }
        }
      }
    }
  },
  "apiConfig": {
    "outbounds": {
      "proxyRequestHandler": {
        "actionName": "handleRequest",
        "parametersMapping": {
          "path": "path"
        }
      }
    }
  },
  "outboundsConfigs": {
    "proxyRequestHandler": {
      "server": {
        "port": "${BACKEND_SERVER_PORT}",
        "host": "${BACKEND_SERVER_HOST}"
      },
      "apiBasePath": "/api"
    }
  }
}
